name: L1-trigger
channels:
- pytorch
- nvidia
- conda-forge
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=12.1
  - matplotlib
  - pandas
  - scikit-learn
  - ipykernel
  - nbformat
  - tensorboard
  - tensorflow
  - scipy
  - hydra-core
  - plotly
  - pyarrow
  - awkward
  - lightning
  - openmpi 
  - mpi4py
  - pip
  - pip: 
      - vector-quantize-pytorch
 
 


